# Setup
title:            Chris F. Nicholson
tagline:          'A place for the things I enjoy.'
description:      'Recipes and some writings by Chris F. Nicholson'
url:              https://www.chrisfnicholson.com
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Chris F. Nicholson'
  url:            https://www.chrisfnicholson.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Theme
style: default
# dark_theme: true
# dark_nav: true

<<<<<<< HEAD
# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
#  - {title: Home, file: "index.html", icon: home}
  - {title: Recipes, icon: utensils, url: "/recipes/"}
  - {title: Cocktails, icon: glass-martini-alt, url: "/drinks/"}
  - {title: Crosswords, icon: crossword, url: "crosswords.html"}

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-datapage-generator
#  - jekyll-responsive-image
#  - jekyll-webp
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-pwa-workbox
  - jekyll_picture_tag

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore
  - vendor
  - Pipfile
  - package.json

page_gen:
  - data: recipes
    template: recipe
    name: name
    dir: recipes
    extension: html

  - data: puzzles
    template: crossword
    name: name
    dir: crosswords
    extension: html

  - data: drinks
    template: drink
    name: name
    title: name
    dir: drinks
    extension: html

# responsive_image:
#  template: _includes/responsive-image.html
#  base_path: assets
#  sizes:
#    - width: 320
#    - width: 480
#    - width: 800

picture:
  source: "assets/"
  output: "assets/generated"
  suppress_warnings: true

pwa:
  enabled: true # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: /js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/assets/images/recipes/*.{ico,png,svg,webp}"
#    - "/assets/images/drinks/*.{ico,png,svg,webp}"
    - "/recipes/*.html"
    - "/drinks/*.html"
    - "/index.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"

staticman_url: https://chrisfnicholson-staticman.herokuapp.com/v2/entry/datapolitical/chrisfnicholson.github.io/main/comments

comments: true

reCaptcha:
  enabled: false
  siteKey_v2: 6Lc2ZnkaAAAAAEMYrdwBDeveZUzFW9mWRcO--6no
  secret_v2: iPME/bOaQsskDaX9gtPcYgvA9o7ePKfHv3uluOSni99jmfQ8dVGaMhGMRPPb3FAOMo4E3EmqbrhMgQYjc3KXK81M1Vzg5oMvgwSQQmJ/ZiAEd6W9udXtYC1f0isv7igbotMYoruKaufxL5f6urpf1nsxRoR3IHRiA/lSB9sbEKfgbrUf0EgTIy+//IcLJ6//5AnOXr/Pxfp5TRZtPUg3aKPgqkOxRp41VuxudkpTdDN0vF5fVEI8YjXPs1Z6o8pRalV2w5t/PfoaAndetMyBevMRm2udxG11gOFxptgTQeJKdIBnvEHYNAcD7jZT+6wQpBOXU+NQ9/G3L9YztYOwnKYkeRW1WpX2anWmu4aBsFoTMkMVuGdz15iVjNAVPDwCvjjqGlFDYACfEtdso+r6m0lFNIiooSBPfyz2uQ9AuqwOXAY1AFgYMqeZQebdo6vtIlAxVuNxPnyfmtFS8OTSmrCVk9RY25Uu/fLKlsaUfXRUiFa8rCRIhrv+g9bVhVphHmH3ZZGmgxTRdo8eqlRPpH2rx4N2YG2IXTzUuwhBwTmQcMhS4krhpEue3zkMscB8Is3qO3qzVeown+dHTTBs3eHyBHZi0WfXAwYKAM+qTO3NpChN5ZL9zbd9r5mVc2XEjS9PBFyjaWsmjLdTEpCnEp6dp+O94lRCgENw5Hs3pHg=
  siteKey: 6Lf3PnkaAAAAAM5SCaPa2yhfSi1EmOw0PtGOB3y9
  secret: BbYECMXkANLYgmOpCENXFqqz2ypjFWKRk8/tKYRzYA3ZMQwmReuIusw8ev6GEBZYdGHCC+fSywJH0jmToJefzg1KusDaJOC5xqzxMFp9t8CrqIpVHoYD3jxHX5ao9iQW7d5Lw34pJgM9k7f+7q/4zIqu+832MuG5pvv3a9ICmVZL08uc0n8vsb2NeDbnIcaxggIR6vOh3A3ExVNs5HQ8NAB5wi8z3G0LJu6tJaIiaua31MT6UwzCkOGDcYs1PpZJd3spIKuUu0t7b1kvA3cpvvSYITJ+LiCIdDDB44lVVr6lLqcLlu1lVSJMeHmq6cZcb9ERylvDn0D7Tue9sKj/q91y1wAH2hnv4vbjeipToR6OMrRdh+r5OpC5f2DZNe1Y1mNebgmgugCuP004SC8IoUbMjoVA/q1AKj6sh9EU0Q0L6DZkj9bO44OXRnrWSbSuy0DhevHRGBX8gQx3ouQZixZ2CTzC33u2viT/YNH8Yd49ZghxWvb/TIs0QIYtbeA3Fs/OD2eKjkLq9JjEA6Ihh1TxTvdbt+gstkk23EP+kIkvHsM7gN3+OwqaN34wI3ybfgA8c24VAsSmQ8pYgxfzzAI0JQUozb3IyJUgWT9J0mbP9X2aeSe8VRp+sVE1ytTmP6PZ53GqaX5xwyA6wCqduwUGQTu17NbKGcJw37qccbY=

############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: false

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["assets/images/recipes", "assets/images/drinks"]

  # Whether to search in nested directories or not
  nested: no

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false
############################################################
