name: temp deploy hook
on: workflow_dispatch

jobs:
  create_deploy_hook:
    runs-on: ubuntu-latest
    if: !contains(github.event.commits[0].message,'[no-ci]')
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: curl
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/contrast-theme/deploy_hooks" \
          -H "X-Auth-Email: ${{ secrets.EMAIL }}" \
          -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -d '{"branch": "${{github.ref_name}}", "name": "${{github.ref_name}}-temp-${{ steps.vars.outputs.sha_short }}"}' \
          -o newhook.json
          echo "hookid=`jq -r ' .result.hook_id' newhook.json`" >> $GITHUB_ENV
      - name: test
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{ env.hookid }}"
      - name: delete
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/contrast-theme/deploy_hooks/${{ENV.hookid}}" \
          -H "X-Auth-Email: ${{ secrets.EMAIL }}" \
          -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_API_TOKEN }}"
